#:schema https://mise.en.dev/schema/mise.json

[hooks]
enter = [
  { shell = "bash", script = "command -v hum >/dev/null && source <(hum completion bash)" },
  { shell = "zsh", script = "command -v hum >/dev/null && source <(hum completion zsh)" },
  { shell = "fish", script = "type -q hum; and hum completion fish | source" },
]

[tools]
colima = "latest"
docker-cli = "latest"
lima = "latest"
mkcert = "latest"
shellcheck = "latest"
task = "latest"
"github:brettinternet/hum" = "latest"

[tools.docker-compose]
version = "latest"
postinstall = '''
mkdir -p ~/.docker/cli-plugins ~/.local/bin
compose_plugin="$(which docker-cli-plugin-docker-compose)"
ln -sf "$compose_plugin" ~/.docker/cli-plugins/docker-compose
ln -sf "$compose_plugin" ~/.local/bin/docker-compose
'''

[settings]
disable_backends = ["asdf", "pipx"]
experimental = true
